### ISSUE TITLE
Docker Integration

### ISSUE THREAD

**Issue by mattgrill** [patrickocoffeyo/drupalcraft#5]
# Docker Integration

I have some thoughts about how this should happen. The Docker integration part of this project should take place in two parts. A client side build task, integrated with the existing Gulp workflow we already have, and a server-side (docker host) application that does the heavy lifting. 

## Client build task

This can actually be pretty simple. Pushing some sort of information to the server, and asking it to start a build. Additionally a web-hook could be made available to automatically build these environments based on branch creation. 

* [ ] Collect data for build server
* [ ] Send data (JSON?) to build server

## Server application

This is where things get potentially tricky. I've already worked out a bunch of this, from the 4k-labs demo I gave earlier this year. However, we'll still have to setup this tool to correctly receive the JSON and then build a container based on that information. 

* [ ] Receive build specific JSON
* [ ] Create temporary mysql database, returning credentials/information. 
* [ ] Run setup tasks based on client-side workflow. 

@patrickocoffeyo If you want to get together to discuss this, lets work on something.

**Comment by patrickocoffeyo** [comment]
Done and merged.
